services:
  ugrainium:
    build: .
    command: "jupyter-lab"
    ports:
      - "8008:8008"
    volumes:
      - type: bind
        source: /home/cyrk/.git-credentials
        target: /home/cyrk/.git-credentials
      - type: bind
        source: /home/cyrk/Downloads
        target: /vol/UGrainium/Downloads
      - type: bind
        source: /vol/UGrainium
        target: /vol/UGrainium

